 module.exports = {
    Transportador: 'Transportador',
    Documentos: 'Documento',
    IncluirContato: 'Contato',
    ExcluirContato: 'Exclusão',
    IncluirEndereco: 'Endereço',
    AlterarEndereco: 'Alterar Endereço',
    ExcluirEndereco: 'Exclusão',
    IncluirGestor: 'Gestor',
    AlterarGestor: 'Alterar Gestor',
    ExcluirGestor: 'Exclusão',
    IncluirMotorista: 'Motorista',
    AlterarMotorista: 'Motorista',
    ExcluirMotorista: 'Exclusão',
    IncluirFilial: 'Filial',
    AlterarFilial: 'Alterar Filial',
    ExcluirFilial: 'Exclusão',
    IncluirResponsavelTecnico: 'Responsável Técnico',
    AlterarResponsavelTecnico: 'Responsável Técnico',
    ExcluirResponsavelTecnico: 'Exclusão',
    IncluirVeiculo: 'Veículo',
    AlterarVeiculo: 'Alterar Veículo',
    ExcluirVeiculo: 'Exclusão'
  };