 module.exports = {
    SalvarTransportador: 'Salvar Transportador',
    EnviarDocumentos: 'Enviar Documentos',
    IncluirContato: 'Incluir Contato',
    ExcluirContato: 'Excluir Contato',
    IncluirEndereco: 'Incluir Endereço',
    AlterarEndereco: 'Alterar Endereço',
    ExcluirEndereco: 'Excluir Endereço',
    IncluirGestor: 'Incluir Gestor',
    AlterarGestor: 'Alterar Gestor',
    ExcluirGestor: 'Excluir Gestor',
    IncluirMotorista: 'Incluir Motorista',
    AlterarMotorista: 'Alterar Motorista',
    ExcluirMotorista: 'Excluir Motorista',
    IncluirFilial: 'Incluir Filial',
    AlterarFilial: 'Alterar Filial',
    ExcluirFilial: 'Excluir Filial',
    IncluirResponsavelTecnico: 'Incluir Responsável Técnico',
    AlterarResponsavelTecnico: 'Alterar Responsável Técnico',
    ExcluirResponsavelTecnico: 'Excluir Responsável Técnico',
    IncluirVeiculo: 'Incluir Veículo',
    AlterarVeiculo: 'Alterar Veículo',
    ExcluirVeiculo: 'Excluir Veículo'
  };