 module.exports = {
    SalvarTransportador: 'Transportador',
    EnviarDocumentos: 'Documento',
    IncluirContato: 'Contato',
    ExcluirContato: 'Excluir Contato',
    IncluirEndereco: 'Incluir Endereço',
    AlterarEndereco: 'Alterar Endereço',
    ExcluirEndereco: 'Excluir Endereço',
    Gestor: 'Gestor',
    AlterarGestor: 'Alterar Gestor',
    ExcluirGestor: 'Excluir Gestor',
    IncluirMotorista: 'Incluir Motorista',
    AlterarMotorista: 'Alterar Motorista',
    ExcluirMotorista: 'Excluir Motorista',
    IncluirFilial: 'Filial',
    AlterarFilial: 'Alterar Filial',
    ExcluirFilial: 'Excluir Filial',
    IncluirResponsavelTecnico: 'Responsável Técnico',
    AlterarResponsavelTecnico: 'Responsável Técnico',
    ExcluirResponsavelTecnico: 'Responsável Técnico',
    IncluirVeiculo: 'Veículo',
    AlterarVeiculo: 'Alterar Veículo',
    ExcluirVeiculo: 'Excluir Veículo'
  };