 module.exports = {
    AGUARDANDOPAGAMENTO: 'AGUARDANDO PAGAMENTO',
    EMCADASTRAMENTO: 'EM CADASTRAMENTO',
    CANCELADO: 'CANCELADO',
    PEDIDOFINALIZADO: 'PEDIDO FINALIZADO',
    PAGAMENTOEFETUADO: 'PAGAMENTO EFETUADO',
    PEDIDOREJEITADO: 'PEDIDO REJEITADO'
  };