module.exports = {
   Acre: 'Acre',
   Alagoas: 'Alagoas',
   Amazonas:'Amazonas',
   Amapa:'Amapá',
   Bahia: 'Bahia',
   Ceara: 'Ceará',
   DistritoFederal:'Distrito Federal',
   EspiritoSanto:'Espirito Santo',
   Goias: 'Goiás',
   Maranhao: 'Maranhão',
   MinasGerais: 'Minas Gerais',
   MatoGrossodoSul: 'Mato Grosso do Sul',
   MatoGrosso: 'Mato Grosso',
   Para: 'Pará',
   Paraiba:'Paraíba',
   Pernambuco: 'Pernambuco',
   Piaui:'Piauí',
   Parana: 'Paraná',
   RiodeJaneiro: 'Rio de Janeiro',
   RioGrandedoNorte: 'Rio Grande do Norte',
   Rondonia: 'Rondônia',
   Roraima: 'Roraima',
   RioGrandedoSul: 'Rio Grande do Sul',
   SantaCatarina: 'Santa Catarina',
   Sergipe: 'Sergipe',
   SaoPaulo: 'São Paulo',
   Tocantins:'Tocantins'
}