import "../e2e/./pages/login.cy";
import "../e2e/./pages/consulta_rntrc_ctc.cy";
import "../e2e/./pages/consulta_rntrc_etc.cy";
import "../e2e/./pages/consulta_rntrc_tac.cy";
import "../e2e/./pages/criar_pedido_alteracao_de_dados_tac.cy";
import "../e2e/./pages/criar_pedido_alteracao_de_dados_etc.cy";
import "../e2e/./pages/criar_pedido_alteracao_de_dados_ctc.cy";
import "../e2e/./pages/criar_pedido_cadastro_tac.cy";
import "../e2e/./pages/criar_pedido_cadastro_etc.cy";
import "../e2e/./pages/criar_pedido_cadastro_ctc.cy";
import "../e2e/./pages/criar_cadastro_usuario_despachante.cy";
import "../e2e/./pages/criar_pedido_inclusao_veiculo_ctc.cy";
import "../e2e/./pages/criar_pedido_inclusao_veiculo_etc.cy";
import "../e2e/./pages/criar_pedido_inclusao_veiculo_tac.cy";
import "../e2e/./pages/criar_pedido_regularizacao_ctc.cy";
import "../e2e/./pages/criar_pedido_regularizacao_etc.cy";
import "../e2e/./pages/criar_pedido_regularizacao_tac.cy";
import "../e2e/./pages/esqueceu_sua_senha_usuario_despachante.cy";
import "../e2e/./pages/fale_conosco_homePage.cy";
import "../e2e/./pages/filtro_consulta_atendimento.cy";
import "../e2e/./pages/navegacao_de_servicos_homePage.cy";
import "../e2e/./pages/pontos_de_atendimento_homePage.cy";

import './pages/integration/sitcarga/cancelar_um_pedido_gerado_a_partir_prepedido_ctc.cy'
import './pages/integration/sitcarga/cancelar_um_pedido_gerado_a_partir_prepedido_etc.cy'
import './pages/integration/sitcarga/cancelar_um_pedido_gerado_a_partir_prepedido_tac.cy'
import './pages/integration/sitcarga/confirmar_pagamento_revalidacao_tac.cy'
import './pages/integration/sitcarga/consultar_saldo_pos_pagamento_revalidacao_tac.cy'
import './pages/integration/sitcarga/finalizar_um_pedido_gerado_a_partir_prepedido_ctc.cy'
import './pages/integration/sitcarga/finalizar_um_pedido_gerado_a_partir_prepedido_etc.cy'
import './pages/integration/sitcarga/finalizar_um_pedido_gerado_a_partir_prepedido_tac.cy'
import './pages/integration/sitcarga/gerar_pedido_apos_confirmacao_pagamento_tac.cy'
import './pages/integration/sitcarga/gerar_pedido_apos_confirmacao_pagamento_etc.cy'
import './pages/integration/sitcarga/gerar_prepedido_rejeitado_ctc.cy'
import './pages/integration/sitcarga/gerar_prepedido_rejeitado_etc.cy'
import './pages/integration/sitcarga/gerar_prepedido_rejeitado_tac.cy'
import './pages/integration/sitcarga/gerar_segunda_via_boleto_revalidacao_tac.cy'
import './pages/integration/sitcarga/verificar_debito_revalidacao_etc.cy'
import './pages/integration/sitcarga/verificar_debito_revalidacao_tac.cy'
import './pages/integration/sitcarga/verificar_pagamento_efetuado_revalidacao_tac.cy'