 module.exports = {
    TransportadorSucesso: 'Transportador salvo com sucesso',
    AtendimentoCanceladoSucesso: 'Atendimento cancelado com sucesso!',
    EdicaoTransportador: 'Edição salva com sucesso!',
    AtendimentoCriadoSucesso: 'Atendimento criado com sucesso!',
    AtendimentofinalizadoSucesso: 'Atendimento finalizado com sucesso!', 
    VeiculoSalvoSucesso: 'Dados salvos com sucesso!',  
    VeiculoAlteracaoSucesso: 'Dados salvos com sucesso!',
    VeiculoExcluidoSucesso: 'Dados salvos com sucesso!',
    CRLVSucesso: 'CRLV incluído com sucesso!',
    OperacaoCanceladaSucesso: 'Operação cancelada com sucesso!',
    CadastroSucesso: 'Cadastro efetuado com sucesso.',
    ContratoArrendamentoSucesso: 'Contrato de arrendamento incluído com sucesso!',
    ArquivoRemovidoSucesso: 'Arquivo removido com sucesso!',
    DadosSalvoSucesso: 'Dados salvos com sucesso!',
    ArquivoInclusoSucesso: 'incluído com sucesso!',
    EnderecoNaoEncontrado: 'Não foi possível retornar o endereço para o CEP informado.',    
    ResponsavelTecnicoJaIncluso: 'Responsável Técnico já incluso no pedido.',
    GestorJaIncluso: 'Gestor já incluso no pedido.',
    GestorNãoExiste: 'Gestor não existe para o transportador.',
    CRLVContratoSucesso: 'CRLV incluído com sucesso!Contrato de arrendamento incluído com sucesso!',
    EmailValidadosSucesso: 'E-mail validado com sucesso.',  
    CodigoEnviadoParaEmail: 'Novo código foi enviado para seu e-mail.',
    NovoCodigoEnviadoEmail: 'Novo código foi enviado para seu e-mail.',
    NovoCodigoEnviadoCelular: 'Novo código foi enviado para seu Celular.',
    EmailEnviadoSucesso: 'E-mail validado com sucesso.'

 };